spring:
  datasource:
    url: jdbc:mysql://localhost:3306/balanced_bison
    hikari:
      connection-timeout: 10000
      max-lifetime: 300000
    username: balancedbisonuser
    password: finance$

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  liquibase:
    url: ${spring.datasource.url}
    user: balancedbison_lbuser
    password: finance$

  server:
    port: 8081
    compression:
      enabled: true
      mime-types: application/json
    use-forward-headers: true